import {
  checkAccessibilityPermission,
  checkPasteTools,
  deleteClipboardImageFiles,
  pasteImage,
  pasteText,
  readClipboard,
  storeClipboardImage,
  writeClipboard,
  writeClipboardImage,
} from "./clipboardCommands";
import {
  onBackendDictationStartFeedback,
  onBackendDictationState,
  onClipboardUpdate,
  onOpenAIRealtimeTranscript,
  onStartDictation,
  onStopDictation,
  onToggleDictation,
  onTranscriptEvent,
  onTranscriptionAdded,
  onTranscriptionDeleted,
  onTranscriptionsCleared,
  onTranscriptionsPruned,
  onVolcengineStreamingTranscript,
} from "./eventCommands";
import {
  setHotkeyListeningMode,
  updateClipboardHotkey,
  updateDictationTriggerMode,
  updateProcessingModeHotkeys,
  updateHotkey,
} from "./hotkeyCommands";
import {
  clearTranscriptions,
  deleteTranscription,
  deleteTranscriptions,
  getDictationTimelineSessions,
  getTranscriptionOutputs,
  getTranscriptionSession,
  getTranscriptions,
  pruneTranscriptionHistory,
  saveDictationTimelineEvents,
  saveTranscription,
  searchTranscriptions,
} from "./historyCommands";
import {
  modelCancelDownload,
  modelCheck,
  modelCheckRuntime,
  modelDelete,
  modelDeleteAll,
  modelDownload,
  modelGetAll,
  modelSelect,
  onModelDownloadProgress,
} from "./modelCompatibilityCommands";
import {
  getForegroundApplication,
  getPrivacyDiagnostics,
  syncForegroundApplicationVocabulary,
} from "./privacyCommands";
import {
  cancelNativeRecording,
  getNativeRecordingCapabilities,
  startAudioDucking,
  startNativeRecording,
  stopAudioDucking,
  stopNativeRecording,
} from "./recordingCommands";
import {
  checkLocalReasoningAvailable,
  processAnthropicReasoning,
  processLocalReasoning,
} from "./reasoningCommands";
import {
  deleteCredential,
  getAllSettings,
  getAnthropicKey,
  getAssemblyAIKey,
  getCredential,
  getCredentialStatus,
  getDebugState,
  getEnvVar,
  getGeminiKey,
  getGroqKey,
  getLogLevel,
  getOpenAIKey,
  getSetting,
  getVolcengineAccessToken,
  getVolcengineAppId,
  getVolcengineResourceId,
  getZaiKey,
  log,
  openLogsFolder,
  saveAllKeysToEnv,
  saveAnthropicKey,
  saveAssemblyAIKey,
  saveGeminiKey,
  saveGroqKey,
  saveOpenAIKey,
  saveVolcengineAccessToken,
  saveVolcengineAppId,
  saveVolcengineResourceId,
  saveZaiKey,
  setCredential,
  setDebugLogging,
  setEnvVar,
  setSetting,
} from "./settingsCommands";
import {
  cancelOpenAIRealtimeTranscription,
  cancelVolcengineStreamingTranscription,
  checkLocalAsrRuntime,
  finishOpenAIRealtimeTranscription,
  finishVolcengineStreamingTranscription,
  getTranscriptionProviders,
  sendOpenAIRealtimeAudio,
  sendVolcengineStreamingAudio,
  startOpenAIRealtimeTranscription,
  startVolcengineStreamingTranscription,
  transcribeAudio,
  transcribeLocalAudio,
} from "./transcriptionCommands";
import {
  checkForUpdates,
  downloadUpdate,
  getAppVersion,
  getUpdateInfo,
  getUpdateStatus,
  installUpdate,
  onUpdateAvailable,
  onUpdateDownloaded,
  onUpdateDownloadProgress,
  onUpdateError,
  onUpdateNotAvailable,
} from "./updaterCommands";
import {
  appQuit,
  cleanupApp,
  getAutoStartEnabled,
  getPlatform,
  hideWindow,
  openAccessibilitySettings,
  openExternal,
  openMicrophoneSettings,
  openSoundInputSettings,
  setAutoStartEnabled,
  setMainWindowInteractivity,
  showControlPanel,
  showDictationPanel,
  showWindow,
  startWindowDrag,
  stopWindowDrag,
  windowClose,
  windowIsMaximized,
  windowMaximize,
  windowMinimize,
} from "./windowCommands";

/**
 * Tauri-backed desktop API kept for legacy global aliases.
 */
export const legacyDesktopAPI = {
  // Logging
  log,
  getLogLevel,

  // Clipboard
  pasteText,
  pasteImage,
  readClipboard,
  writeClipboard,
  writeClipboardImage,
  storeClipboardImage,
  deleteClipboardImageFiles,
  onClipboardUpdate,
  checkPasteTools,
  checkAccessibilityPermission,

  // Database
  saveTranscription,
  getTranscriptions,
  searchTranscriptions,
  getTranscriptionOutputs,
  getTranscriptionSession,
  saveDictationTimelineEvents,
  getDictationTimelineSessions,
  deleteTranscription,
  deleteTranscriptions,
  clearTranscriptions,
  pruneTranscriptionHistory,

  // Transcription
  transcribeAudio,
  transcribeLocalAudio,
  checkLocalAsrRuntime,
  startVolcengineStreamingTranscription,
  sendVolcengineStreamingAudio,
  finishVolcengineStreamingTranscription,
  cancelVolcengineStreamingTranscription,
  startOpenAIRealtimeTranscription,
  sendOpenAIRealtimeAudio,
  finishOpenAIRealtimeTranscription,
  cancelOpenAIRealtimeTranscription,
  getTranscriptionProviders,

  // Native Recording
  getNativeRecordingCapabilities,
  startNativeRecording,
  stopNativeRecording,
  cancelNativeRecording,

  // System Audio Ducking
  startAudioDucking,
  stopAudioDucking,

  // Settings
  getSetting,
  setSetting,
  getCredential,
  getCredentialStatus,
  setCredential,
  deleteCredential,
  getEnvVar,
  setEnvVar,
  getAllSettings,
  getDebugState,
  setDebugLogging,
  openLogsFolder,
  getAssemblyAIKey,
  getOpenAIKey,
  saveAssemblyAIKey,
  saveOpenAIKey,
  getAnthropicKey,
  saveAnthropicKey,
  getGeminiKey,
  saveGeminiKey,
  getGroqKey,
  saveGroqKey,
  getZaiKey,
  saveZaiKey,
  getVolcengineAppId,
  saveVolcengineAppId,
  getVolcengineAccessToken,
  saveVolcengineAccessToken,
  getVolcengineResourceId,
  saveVolcengineResourceId,

  // Window
  showDictationPanel,
  showControlPanel,
  hideWindow,
  showWindow,
  startWindowDrag,
  stopWindowDrag,
  getPlatform,
  getForegroundApplication,
  syncForegroundApplicationVocabulary,
  getPrivacyDiagnostics,
  windowMinimize,
  windowMaximize,
  windowClose,
  windowIsMaximized,

  // Events
  onToggleDictation,
  onStartDictation,
  onStopDictation,
  onTranscriptEvent,
  onVolcengineStreamingTranscript,
  onOpenAIRealtimeTranscript,
  onTranscriptionAdded,
  onTranscriptionDeleted,
  onTranscriptionsCleared,
  onTranscriptionsPruned,
  onBackendDictationState,
  onBackendDictationStartFeedback,

  // App
  appQuit,
  openExternal,
  openMicrophoneSettings,
  openSoundInputSettings,
  openAccessibilitySettings,

  // Updater
  checkForUpdates,
  downloadUpdate,
  installUpdate,
  getAppVersion,
  getUpdateStatus,
  getUpdateInfo,
  onUpdateAvailable,
  onUpdateNotAvailable,
  onUpdateDownloaded,
  onUpdateDownloadProgress,
  onUpdateError,

  // Autostart
  getAutoStartEnabled,
  setAutoStartEnabled,

  // Hotkey
  updateHotkey,
  updateClipboardHotkey,
  updateDictationTriggerMode,
  updateProcessingModeHotkeys,
  setHotkeyListeningMode,
  setMainWindowInteractivity,
  saveAllKeysToEnv,
  cleanupApp,

  // Stub for missing functions
  onHotkeyFallbackUsed: (_callback: any) => () => {},
  onHotkeyRegistrationFailed: (_callback: any) => () => {},
  onGlobeKeyPressed: (_callback: any) => () => {},
  modelGetAll,
  modelCheck,
  modelDownload,
  modelDelete,
  modelDeleteAll,
  modelCheckRuntime,
  modelCancelDownload,
  modelSelect,
  onModelDownloadProgress,
  processLocalReasoning,
  checkLocalReasoningAvailable,
  processAnthropicReasoning,
};

export type LegacyDesktopAPI = typeof legacyDesktopAPI;
